language: cpp

install:
  - sudo git clone https://github.com/KulArtV/base_testing -b vector_test
  - cd base_testing
  - ls -a
  - cd ..
  - ls -a
  - sudo cp vector.h base_testing
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libgtest-dev
  - mkdir build_gtest
  - cd build_gtest
  - cmake /usr/src/gtest
  - sudo make
  - sudo cp libgtest* /usr/lib
  - cd ..


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./Test
  - cd CMakeFiles/Test.dir
  - cd ..
  - cd ..
